language: c

os:
  - linux

addons:
  apt:
    packages:
      - texlive-latex-base
      - texlive-latex-recommended
      - texlive-latex-extra
      - texlive-fonts-recommended
      - latex-xcolor
      - xsltproc

before_install:
  - make biblio forcetex html

script:
  - test -f ADQL.pdf
  - test -f ADQL.html
  - test -f ADQL.bbl
